app = "telegram-lottery-bot"

[env]
  BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"

[build]
  builder = "heroku/buildpacks:20"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
